services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alphyRaCKyhO
      POSTGRES_PASSWORD: n24h|R}IQx<MOx:>7ulm1
      POSTGRES_DB: postgres
  frontend:
    build: .
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - database