name: CI to Docker Registry

on:
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/neova-waitlist-frontend:latest
          push: true
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/neova-waitlist-backend:latest
          push: true