name: CI to Docker Registry

on:
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.neova.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: harbor.neova.io/neova/neova-waitlist-frontend:latest
          push: true
          
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.neova.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile
          tags: harbor.neova.io/neova/neova-waitlist-backend:latest
          push: true