name: CI to Docker Registry

on:
  workflow_dispatch:
  push:
    branches:
      - prod

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.neova.io
          username: robot$robot-github
          password: ${{ secrets.HARBOR_ROBOT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: harbor.neova.io/prod/waitlist-frontend:latest
          push: true
          
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.neova.io
          username: robot$robot-github
          password: ${{ secrets.HARBOR_ROBOT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile
          tags: harbor.neova.io/prod/waitlist-api:latest
          push: true